[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"
default-run = 'day_3'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

